name: Documentation Generation

on:
  push:
    branches: [ "main" ]

jobs:
    build:
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v3
            - name: Run generate_docs.sh
              run: bash generate_docs.sh
            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: docs
                FOLDER: .docs
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MESSAGE: "automated build: ({sha}) {msg}"